name: Deploy FastAPI via Git Pull

on:
  push:
    branches:
      - refactor 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into EC2 and deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~
          git reset --hard
          git pull origin refactor
          source venv/bin/activate
          pip install --upgrade 
          pip install -r requirements.txt
          sudo systemctl restart fastapi
